/** Per-brand auxiliary files included in each export folder. */

/** Filesystem-safe folder/file slug for a brand name. */
export function slugify(brand: string): string {
  const s = brand
    .trim()
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, "-")
    .replace(/^-+|-+$/g, "");
  return s || "brand";
}

export function manifestJson(brand: string, themeColor: string, bgColor: string): string {
  return JSON.stringify(
    {
      name: brand,
      short_name: brand,
      icons: [
        { src: "/android-chrome-192x192.png", sizes: "192x192", type: "image/png" },
        { src: "/android-chrome-512x512.png", sizes: "512x512", type: "image/png" },
      ],
      theme_color: themeColor,
      background_color: bgColor,
      display: "standalone",
    },
    null,
    2,
  );
}

export function browserConfigXml(themeColor: string): string {
  return `<?xml version="1.0" encoding="utf-8"?>
<browserconfig>
  <msapplication>
    <tile>
      <square150x150logo src="/android-chrome-192x192.png"/>
      <TileColor>${themeColor}</TileColor>
    </tile>
  </msapplication>
</browserconfig>
`;
}

export function htmlSnippet(brand: string, themeColor: string): string {
  return `<!-- ${brand} favicon — generated by Йоба генератор фавиконок от Akuma no SEO -->
<link rel="icon" type="image/x-icon" href="/favicon.ico">
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-config" content="/browserconfig.xml">
<meta name="theme-color" content="${themeColor}">
`;
}

/** Maps an export size to its canonical output filename. */
export function fileNameForSize(size: number): string {
  switch (size) {
    case 180:
      return "apple-touch-icon.png";
    case 192:
      return "android-chrome-192x192.png";
    case 512:
      return "android-chrome-512x512.png";
    default:
      return `favicon-${size}.png`;
  }
}
