import type { Preset } from "@/lib/types";

/**
 * Template presets — each defines a base look plus the pools the bulk
 * generator draws from to stay on-theme while maximizing variety.
 */
export const PRESETS: Preset[] = [
  {
    id: "casino",
    name: "Casino",
    description: "Rich reds & golds, bold display type",
    palette: ["#e63946", "#7209b7", "#ffd166", "#1a1a2e", "#f77f00", "#9b5de5"],
    fonts: ["anton", "bungee", "archivo", "russo"],
    shapes: ["rounded", "circle", "squircle"],
    apply: { bgColor: "#7209b7", textColor: "#ffd166", fontFamily: "bungee", shape: "rounded", cornerRadius: 110, fontSize: 230 },
  },
  {
    id: "sportsbook",
    name: "Sportsbook",
    description: "Energetic blues & greens, condensed type",
    palette: ["#06d6a0", "#118ab2", "#457b9d", "#073b4c", "#2a9d8f", "#4361ee"],
    fonts: ["oswald", "teko", "rajdhani", "montserrat"],
    shapes: ["square", "rounded", "hexagon"],
    apply: { bgColor: "#118ab2", textColor: "#ffffff", fontFamily: "teko", shape: "rounded", cornerRadius: 70, fontSize: 280, fontWeight: 600 },
  },
  {
    id: "crypto",
    name: "Crypto",
    description: "Neon gradients, futuristic geometry",
    palette: ["#06d6a0", "#4361ee", "#9b5de5", "#1a1a2e", "#3a0ca3", "#118ab2"],
    fonts: ["orbitron", "exo2", "rajdhani"],
    shapes: ["hexagon", "squircle", "circle"],
    apply: {
      bgColor: "#1a1a2e",
      textColor: "#06d6a0",
      fontFamily: "orbitron",
      shape: "hexagon",
      fontSize: 200,
      fontWeight: 700,
      textGradient: { enabled: true, from: "#06d6a0", to: "#4361ee", angle: 120 },
      effects: { textShadow: false, glow: true, neon: false, blur: 0, innerShadow: false, outerShadow: false, metallic: false, glass: false, noise: false },
    },
  },
  {
    id: "esports",
    name: "Esports",
    description: "Aggressive angles, high contrast",
    palette: ["#ef476f", "#9b5de5", "#06d6a0", "#1a1a2e", "#e63946", "#4361ee"],
    fonts: ["bungee", "anton", "russo", "archivo"],
    shapes: ["hexagon", "square", "rounded"],
    apply: { bgColor: "#1a1a2e", textColor: "#ef476f", fontFamily: "russo", shape: "hexagon", fontSize: 210, italic: 8 },
  },
  {
    id: "luxury",
    name: "Luxury",
    description: "Black & gold, elegant serif",
    palette: ["#0a0a0a", "#ffd166", "#e9c46a", "#073b4c", "#333333", "#f4a261"],
    fonts: ["cinzel", "montserrat", "poppins"],
    shapes: ["circle", "rounded", "square"],
    apply: {
      bgColor: "#0a0a0a",
      textColor: "#e9c46a",
      fontFamily: "cinzel",
      shape: "circle",
      fontSize: 210,
      fontWeight: 700,
      borderWidth: 10,
      borderColor: "#e9c46a",
      effects: { textShadow: false, glow: false, neon: false, blur: 0, innerShadow: false, outerShadow: false, metallic: true, glass: false, noise: false },
    },
  },
  {
    id: "neon",
    name: "Neon",
    description: "Glowing tubes on near-black",
    palette: ["#ef476f", "#06d6a0", "#9b5de5", "#ffd166", "#4361ee", "#1a1a2e"],
    fonts: ["orbitron", "exo2", "bungee", "rajdhani"],
    shapes: ["rounded", "squircle", "circle"],
    apply: {
      bgColor: "#0a0a0a",
      textColor: "#ef476f",
      fontFamily: "exo2",
      shape: "rounded",
      cornerRadius: 110,
      fontSize: 220,
      fontWeight: 800,
      effects: { textShadow: false, glow: false, neon: true, blur: 0, innerShadow: false, outerShadow: false, metallic: false, glass: false, noise: false },
    },
  },
  {
    id: "dark-betting",
    name: "Dark Betting",
    description: "Moody dark palette, restrained accent",
    palette: ["#073b4c", "#264653", "#1a1a2e", "#e63946", "#2a9d8f", "#333333"],
    fonts: ["oswald", "montserrat", "rajdhani", "inter"],
    shapes: ["rounded", "square", "squircle"],
    apply: { bgColor: "#264653", textColor: "#e63946", fontFamily: "oswald", shape: "rounded", cornerRadius: 80, fontSize: 250, fontWeight: 700 },
  },
  {
    id: "futuristic",
    name: "Futuristic",
    description: "Glass + metallic, tech vibe",
    palette: ["#4361ee", "#118ab2", "#06d6a0", "#1a1a2e", "#9b5de5", "#3a0ca3"],
    fonts: ["orbitron", "exo2", "rajdhani"],
    shapes: ["squircle", "hexagon", "rounded"],
    apply: {
      bgColor: "#3a0ca3",
      textColor: "#ffffff",
      fontFamily: "orbitron",
      shape: "squircle",
      fontSize: 200,
      bgGradient: { enabled: true, from: "#3a0ca3", to: "#4361ee", angle: 135 },
      effects: { textShadow: false, glow: false, neon: false, blur: 0, innerShadow: false, outerShadow: false, metallic: false, glass: true, noise: false },
    },
  },
  {
    id: "retro-arcade",
    name: "Retro Arcade",
    description: "Chunky pixels & vivid pop colors",
    palette: ["#ffd166", "#ef476f", "#06d6a0", "#4361ee", "#f77f00", "#7209b7"],
    fonts: ["bungee", "russo", "anton"],
    shapes: ["square", "rounded"],
    apply: {
      bgColor: "#ef476f",
      textColor: "#ffd166",
      fontFamily: "bungee",
      shape: "square",
      fontSize: 220,
      effects: { textShadow: true, glow: false, neon: false, blur: 0, innerShadow: false, outerShadow: false, metallic: false, glass: false, noise: false },
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Flat, clean, single accent",
    palette: ["#1a1a2e", "#e63946", "#457b9d", "#2a9d8f", "#333333", "#ffffff"],
    fonts: ["inter", "montserrat", "poppins", "archivo"],
    shapes: ["rounded", "circle", "square"],
    apply: { bgColor: "#1a1a2e", textColor: "#ffffff", fontFamily: "inter", shape: "rounded", cornerRadius: 96, fontSize: 240, fontWeight: 800 },
  },
];

export const PRESET_BY_ID = new Map(PRESETS.map((p) => [p.id, p]));
